### ISSUE TITLE
Python script issue, while training yolov5l6_640_ti_lite & yolov5m6_640_ti_lite on custom dataset.

### ISSUE THREAD

**Issue by p-kedar-07** [TexasInstruments/edgeai-modelmaker#8]
**While training custom dataset on above mentioned model, found some issue in respective python scripts.**

**Error log :**
Traceback (most recent call last):
 File "./scripts/run_modelmaker.py", line 128, in <module>
  main(config)
 File "./scripts/run_modelmaker.py", line 69, in main
  model_runner.run()
 File "/home/a0504102/alpd_workbench/work_bench_1/tidl/edgeai-modelmaker/edgeai_modelmaker/ai_modules/vision/runner.py", line 158, in run
  self.model_training.run()
 File "/home/a0504102/alpd_workbench/work_bench_1/tidl/edgeai-modelmaker/edgeai_modelmaker/ai_modules/vision/training/edgeai_yolov5/detection.py", line 374, in run
  disable_git_status=True)
 File "/home/a0504102/alpd_workbench/work_bench_1/tidl/edgeai-yolov5/train.py", line 588, in run
  main(opt)
 File "/home/a0504102/alpd_workbench/work_bench_1/tidl/edgeai-yolov5/train.py", line 492, in main
  train(opt.hyp, opt, device)
 File "/home/a0504102/alpd_workbench/work_bench_1/tidl/edgeai-yolov5/train.py", line 223, in train
  plot_labels(labels, names, save_dir, loggers)
 File "/home/a0504102/alpd_workbench/work_bench_1/tidl/edgeai-yolov5/utils/plots.py", line 329, in plot_labels
  loggers.log_images(save_dir.glob('labels.jpg'))
 File "/home/a0504102/alpd_workbench/work_bench_1/tidl/edgeai-yolov5/utils/loggers/init.py", line 142, in log_images
  self.wandb.log({"Labels": [wandb.Image(str(x), caption=x.name) for x in paths]})
 File "/home/a0504102/alpd_workbench/work_bench_1/tidl/edgeai-yolov5/utils/loggers/init.py", line 142, in <listcomp>
  self.wandb.log({"Labels": [wandb.Image(str(x), caption=x.name) for x in paths]})
AttributeError: 'NoneType' object has no attribute 'Image'

**Comment by mathmanu** [comment]
What is in your PYTHONPATH? That might give me a clue.
echo $PYTHONPATH

Also can you comment out these lines 41 to 46 and try again?
https://github.com/TexasInstruments/edgeai-yolov5/blob/master/utils/loggers/__init__.py#L41
The import there might import the local folder instead of the python package if your PYTHONPATH starts with a . or :

**Comment by mathmanu** [comment]
I have gone ahead and added a fix that I think will work for you. Please pull the repository and run again and see if it resolves the issue.

**Comment by p-kedar-07** [comment]
Team,
After pulling latest changes, i am still facing same issue.
$PYTHONPATH is set to .:
